In [1]:
from BPE import BPE

import torch

from GPT import GPT

In [2]:
vocab_size = 31
emb_size = 64
max_seq_len = 100
head_size = 4
num_heads = 8
num_layers = 2
dropout = 0.1

In [3]:
r1 = torch.randint(1, vocab_size, [3,10])
r1

tensor([[ 9, 27,  7, 26,  5,  9, 27, 16, 11, 13],
        [23, 19, 19, 15, 22, 23, 16, 13, 21, 13],
        [ 5, 30, 20,  3, 21, 25, 24, 25,  9,  1]])

In [4]:
gpt = GPT(
    vocab_size=vocab_size,
    max_seq_len=max_seq_len,
    emb_size=emb_size,
    num_heads=num_heads,
    head_size=head_size,
    num_layers=num_layers,
    dropout=dropout
)

In [5]:
output = gpt(r1)
output

tensor([[[-7.2591e-01, -3.6854e-01,  1.0954e+00,  8.3892e-01,  6.2137e-01,
           1.1589e+00, -6.3288e-01,  1.4185e-02,  6.1331e-01,  1.3343e-01,
          -2.4361e-01, -4.9267e-01,  2.3373e-01,  4.2468e-01,  5.4926e-01,
          -1.2065e+00,  9.6573e-01, -5.9754e-01,  3.1319e-01, -6.2322e-01,
          -3.3597e-02,  5.6987e-01, -1.4186e-01,  8.4570e-01, -4.6502e-01,
           7.2223e-02, -1.0036e-01,  1.5954e-01, -3.4493e-01, -2.5786e-01,
           3.1979e-01],
         [-1.0657e+00,  4.1372e-02,  4.1034e-01,  6.1894e-01,  6.2967e-01,
           5.4026e-01, -1.3923e-01,  4.9120e-01, -3.5896e-01,  4.3331e-01,
          -9.3539e-01, -6.6429e-01,  5.8687e-01, -2.2165e-01,  6.2553e-01,
          -1.2964e-01,  1.2035e+00, -2.5611e-01, -7.4250e-01,  1.5747e-01,
          -5.5625e-01,  3.3710e-01, -5.8821e-02,  6.2893e-01,  2.6704e-01,
           8.4814e-01, -1.3583e-01, -5.8462e-01, -4.5995e-01, -5.0715e-02,
           5.6119e-01],
         [-5.3466e-01, -4.2134e-02,  6.0915e-01, -2.

In [6]:
gpt.generate(r1, 20)

tensor([[ 9, 27,  7, 26,  5,  9, 27, 16, 11, 13,  6, 29, 24,  9, 16,  7, 26,  6,
         29,  4, 26, 10, 16, 24,  2, 19,  6,  9, 18, 12],
        [23, 19, 19, 15, 22, 23, 16, 13, 21, 13, 18, 18, 16, 24,  8, 21, 21, 16,
         30, 29,  2, 29,  6,  6, 19,  4, 26,  3, 19, 30],
        [ 5, 30, 20,  3, 21, 25, 24, 25,  9,  1,  6, 29, 16, 24,  8, 11,  6, 29,
         16, 29,  2, 28, 19,  4,  2, 28, 10,  3,  7, 20]])

In [7]:
text = "Однажды был случай в далёком Макао: макака коалу в какао макала, коала лениво какао лакала, макака макала, коала икала."

In [8]:
bpe = BPE(vocab_size=vocab_size)

In [9]:
bpe.fit(text)

In [10]:
bpe.encode("Однажды был случай")

[5, 9, 17, 6, 11, 9, 22, 0, 7, 22, 15, 0, 19, 15, 20, 21, 6, 13]

In [11]:
bpe.decode([5, 9, 17, 6, 11, 9, 22, 0, 7, 22, 15, 0, 19, 15, 20, 21, 6, 13])

'Однажды был случай'