In [1]:
from BPE import BPE

import torch

from GPT import GPT

In [2]:
vocab_size = 31
emb_size = 64
max_seq_len = 100
head_size = 4
num_heads = 8
num_layers = 2
dropout = 0.1

In [3]:
r1 = torch.randint(1, vocab_size, [3,10])
r1

tensor([[ 1, 17, 26, 29, 26, 26, 21,  5, 12,  9],
        [ 2, 26, 10, 22, 29, 30,  4, 16,  2, 20],
        [21,  8, 17, 15,  7, 23, 25, 18, 12, 17]])

In [4]:
gpt = GPT(
    vocab_size=vocab_size,
    max_seq_len=max_seq_len,
    emb_size=emb_size,
    num_heads=num_heads,
    head_size=head_size,
    num_layers=num_layers,
    dropout=dropout
)

In [5]:
output = gpt(r1)
output

tensor([[[-7.1854e-01, -2.3681e-01, -1.9020e-01, -1.8518e-02, -6.0196e-01,
          -4.5449e-01, -1.5053e-01,  1.1612e-01,  2.5070e-01, -3.1603e-01,
          -5.9266e-01,  2.2477e-01, -2.8765e-03,  5.8645e-01, -2.5693e-01,
          -5.3064e-01, -3.1720e-02,  6.5888e-01, -8.7760e-02, -5.7204e-01,
           1.6179e-01, -2.8689e-01, -2.3742e-01, -1.8794e-01,  3.0337e-01,
          -2.0736e-01, -1.1623e+00, -3.2635e-01,  4.3762e-01,  1.2968e+00,
          -2.7153e-01],
         [ 1.0694e-01, -4.5248e-01,  1.1276e-03, -5.1435e-02, -7.2781e-01,
           3.1449e-01,  4.2381e-01,  7.5234e-01, -6.8982e-01, -3.1673e-01,
          -6.1620e-01,  1.0604e+00, -4.3084e-01,  4.3570e-01,  7.7604e-01,
           3.5630e-01, -4.0239e-01, -3.8967e-01, -1.4301e-01, -7.1735e-01,
           8.3869e-01, -6.6616e-01,  1.7055e-01, -4.7206e-01, -6.1770e-02,
           3.6371e-02, -9.2858e-01,  7.3509e-01, -3.2011e-01,  6.8179e-01,
          -2.6368e-01],
         [ 9.6275e-01,  5.7171e-01,  8.8889e-01,  4.

In [16]:
gpt.generate(r1, 20, True)

tensor([[ 1, 17, 26, 29, 26, 26, 21,  5, 12,  9, 30,  0,  5, 26, 21, 21,  8,  8,
         15, 23, 30,  0,  8, 28,  7,  8, 21,  7, 11, 30],
        [ 2, 26, 10, 22, 29, 30,  4, 16,  2, 20, 11, 25, 18,  1,  9, 23, 27,  8,
          0, 25, 26, 20,  2,  1, 27,  3, 28, 29, 26, 26],
        [21,  8, 17, 15,  7, 23, 25, 18, 12, 17, 29, 23, 23, 16,  7, 27,  9, 24,
         22, 16,  8, 25, 22, 30, 29,  7, 27,  4, 25,  5]])

In [7]:
text = "Однажды был случай в далёком Макао: макака коалу в какао макала, коала лениво какао лакала, макака макала, коала икала."

In [8]:
bpe = BPE(vocab_size=vocab_size)

In [9]:
bpe.fit(text)

In [10]:
bpe.encode("Однажды был случай")

[5, 9, 17, 6, 11, 9, 22, 0, 7, 22, 15, 0, 19, 15, 20, 21, 6, 13]

In [11]:
bpe.decode([5, 9, 17, 6, 11, 9, 22, 0, 7, 22, 15, 0, 19, 15, 20, 21, 6, 13])

'Однажды был случай'