In [1]:
from BPE import BPE
from GPT import GPT

import torch

In [2]:
vocab_size = 31
emb_size = 64
max_seq_len = 100
head_size = 4
num_heads = 8
num_layers = 2
dropout = 0.1

In [3]:
r1 = torch.randint(1, vocab_size, [3,10])
r1

tensor([[16, 23, 17,  3, 11,  7, 20,  3, 22, 27],
        [23, 14, 12, 10,  6,  2,  1,  1,  6, 25],
        [20, 14,  2, 20, 21,  4,  7, 21, 11, 16]])

In [4]:
gpt = GPT(
    vocab_size=vocab_size,
    max_seq_len=max_seq_len,
    emb_size=emb_size,
    num_heads=num_heads,
    head_size=head_size,
    num_layers=num_layers,
    dropout=dropout
)

In [5]:
output = gpt(r1)
output

tensor([[[-1.0557e+00, -4.9091e-01,  3.1827e-01,  7.2697e-01,  2.9437e-01,
          -5.7672e-01,  5.8142e-01,  5.1729e-01, -5.3969e-01, -6.0626e-01,
           5.3169e-01,  8.1511e-01, -1.3720e+00,  4.7520e-01,  1.8904e-01,
           2.7556e-01, -6.1878e-01,  3.8160e-01,  1.8935e-01, -3.7141e-01,
          -5.4929e-01, -8.3274e-01, -8.3341e-01,  7.7807e-01,  9.5760e-01,
           2.9040e-01, -5.4046e-01,  1.3704e+00, -1.2036e+00,  4.2204e-01,
           1.1139e+00],
         [ 1.0850e-01, -8.6912e-02, -4.3483e-01,  8.3229e-01,  2.4962e-01,
           1.1937e-01, -3.3014e-01,  3.2224e-01, -4.1530e-01,  1.3672e-01,
           4.4624e-01, -7.8358e-01, -5.6641e-02, -7.2930e-01, -3.6859e-01,
          -4.1681e-01, -1.6385e-01,  5.7262e-01,  4.9605e-01, -1.1306e-01,
          -1.1812e+00,  1.4121e-01, -4.2812e-01,  8.1534e-01,  6.9167e-01,
          -5.3084e-01, -7.6104e-02,  3.0913e-01,  3.7478e-01, -7.7610e-03,
           7.8557e-01],
         [ 4.1772e-01,  1.3220e-01, -7.8832e-01,  4.

In [6]:
gpt.generate(r1, 20, True)

tensor([[16, 23, 17,  3, 11,  7, 20,  3, 22, 27, 15, 10,  2, 13, 10, 25, 19, 17,
         18, 20,  1, 23, 10, 22, 29,  1, 10, 11, 19,  1],
        [23, 14, 12, 10,  6,  2,  1,  1,  6, 25, 27, 30,  9, 27, 10, 22, 19, 12,
          9, 30, 26,  8, 28,  6, 24,  3, 21, 23,  3, 13],
        [20, 14,  2, 20, 21,  4,  7, 21, 11, 16, 27, 17,  7, 11,  8,  6, 27, 21,
         17, 17, 12,  6,  7, 12, 14, 19, 14,  2,  5, 30]])

In [7]:
text = "Однажды был случай в далёком Макао: макака коалу в какао макала, коала лениво какао лакала, макака макала, коала икала."

In [8]:
bpe = BPE(vocab_size=vocab_size)

In [9]:
bpe.fit(text)

In [10]:
enc = bpe.encode("Однажды был случай")
enc

[5, 9, 17, 6, 11, 9, 22, 0, 7, 22, 15, 0, 19, 15, 20, 21, 6, 13]

In [11]:
dec = bpe.decode(enc)
dec

'Однажды был случай'