In [1]:
from BPE import BPE
from GPT import GPT

import torch

In [2]:
vocab_size = 31
emb_size = 64
max_seq_len = 100
head_size = 4
num_heads = 8
num_layers = 2
dropout = 0.1

In [3]:
r1 = torch.randint(1, vocab_size, [3,10])
r1

tensor([[26, 26, 17, 11,  3, 22, 12,  3, 24, 22],
        [27, 26, 26, 11, 30, 13, 15, 18, 24,  8],
        [ 7,  9, 23,  4,  3, 30,  8, 17, 21, 14]])

In [4]:
gpt = GPT(
    vocab_size=vocab_size,
    max_seq_len=max_seq_len,
    emb_size=emb_size,
    num_heads=num_heads,
    head_size=head_size,
    num_layers=num_layers,
    dropout=dropout
)

In [5]:
output = gpt(r1)
output

tensor([[[-2.2621e-02,  2.3736e-02,  1.6253e-01, -1.0427e+00, -4.3244e-01,
           1.7145e-01, -4.3667e-01, -1.2677e-01,  4.8527e-01, -8.3245e-01,
          -7.1013e-01,  1.2396e+00, -9.7923e-01, -6.2772e-01,  8.1623e-01,
          -1.4861e+00,  6.2831e-01,  2.2512e-01, -3.9526e-01, -5.4650e-01,
          -4.7538e-01,  9.9370e-01,  5.3513e-01, -1.1998e+00, -1.1766e+00,
           4.8122e-01,  1.0482e-01,  3.4990e-01, -1.6014e+00,  2.9827e-01,
          -1.6584e-01],
         [ 1.5161e-02,  2.3313e-01, -3.6707e-01, -2.5616e-02,  7.7563e-02,
           5.0474e-01, -1.0699e-01, -5.7685e-02,  8.4983e-01, -5.0819e-01,
          -1.0805e+00,  9.1624e-01, -1.0510e+00, -7.4510e-01,  5.1058e-01,
          -1.7085e+00,  6.4999e-01, -1.0925e-01, -3.9508e-01, -5.2453e-01,
          -1.0123e+00, -4.6127e-02,  4.8086e-02, -1.2501e+00, -4.7986e-01,
           1.4770e+00,  3.5435e-01,  2.1818e-01, -2.1820e-01,  5.9434e-01,
          -4.0919e-01],
         [ 6.7210e-01, -1.3072e-01,  3.4104e-02,  2.

In [6]:
gpt.generate(r1, 20, True)

tensor([[26, 26, 17, 11,  3, 22, 12,  3, 24, 22, 17,  5, 22, 22, 11, 15, 16,  8,
         25, 28, 22, 29, 15, 16,  8, 16, 10, 28,  2, 16],
        [27, 26, 26, 11, 30, 13, 15, 18, 24,  8, 23, 21, 30, 18,  3,  0, 30, 25,
          6,  6,  2, 25,  8,  2, 16,  9, 16, 10, 25, 10],
        [ 7,  9, 23,  4,  3, 30,  8, 17, 21, 14, 11,  8, 26, 19, 20, 25, 14, 16,
         10,  5, 23,  5, 30, 22, 12, 29, 27, 24, 23, 10]])

In [7]:
text = "Однажды был случай в далёком Макао: макака коалу в какао макала, коала лениво какао лакала, макака макала, коала икала."

In [8]:
bpe = BPE(vocab_size=vocab_size)

In [9]:
bpe.fit(text)

In [10]:
enc = bpe.encode("Однажды был случай")
enc

[5, 9, 17, 6, 11, 9, 22, 0, 7, 22, 15, 0, 19, 15, 20, 21, 6, 13]

In [11]:
dec = bpe.decode(enc)
dec

'Однажды был случай'